# Script Generated by Control Surface Studio for Python 3 (resorted to default: no)
from .custom_control_script import custom_control_script

def create_instance(control_surface):
	return custom_control_script(control_surface)